In [6]:
#%lsmagic # by using this command we can get the all magic words 

In [26]:
import numpy as np
array=np.array([
    [1,2,3],
    [4,5,6]
])   # make a specific data type in numpy

In [27]:
print(array)

[[1 2 3]
 [4 5 6]]


In [28]:
array*array   # yeh apne sey khud multiply hota hai ,mean khud ke element sey multiple hota hai
# jaise 1*1=1 and 2*2=4....

array([[ 1,  4,  9],
       [16, 25, 36]])

In [29]:
array**array        # it like 1 to the power 1 and 2 to the power 2 and 9 to the power 9  so on...

array([[    1,     4,    27],
       [  256,  3125, 46656]], dtype=int32)

# slicing in a numpy

In [33]:
array[0:1,0:5]  # slicing in a numpy array
 # first it take 0 sey less than 1 dimesntion takh ka array,1 is excluded
# second leyga 0 sey less than 5 takh ke element from 0 dimention

array([[1, 2, 3]])